version: "3"

services:
    server:
        image: hiroki/go-server:latest
        container_name: goserver
        ports: 
            - "8080:8080"
        depends_on:
            - db
        volumes: 
            - ./go-server:/go/src/work

    db:
        image: mysql:8.0.20
        container_name: mysql_db
        environment: 
            MYSQL_ROOT_PASSWORD: root_pass
            MYSQL_DATABASE: furukawa_seminer
            MYSQL_USER: hiroki
            MYSQL_PASSWORD: hiroki_pass
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        ports:
            - "3306:3306"
        volumes: 
            - ./db/initdb.d:/docker-entrypoint-initdb.d